apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dify-backend-pvc
  namespace: dify
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: nutanix-nfs
