apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-web
  template:
    metadata:
      labels:
        app: dify-web
    spec:
      containers:
        - name: dify-web
          image: "{{ required "images.web.repository is required" .Values.images.web.repository }}:{{ required "images.web.tag is required" .Values.images.web.tag }}"
          envFrom:
            - secretRef:
                name: dify-secrets
          env:
            - name: SERVER_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: CONSOLE_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: APP_API_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: CONSOLE_API_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: CONSOLE_WEB_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: APP_WEB_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: SERVICE_API_URL
              value: "{{ include "dify.externalURL" . }}/v1"
            - name: FILES_URL
              value: "{{ include "dify.externalURL" . }}/files"
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          # リソースやlivenessProbe等は後続で調整
---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dify-web
  ports:
    - port: 80
      targetPort: 3000

