apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-web
  template:
    metadata:
      labels:
        app: dify-web
    spec:
      containers:
        - name: dify-web
          image: "{{ .Values.images.web.repository | default "langgenius/dify-web" }}:{{ .Values.images.web.tag | default .Values.images.tag | default "1.11.4" }}"
          env:
            # External URLs (相対パスで動作、external.host不要)
            # Note: 相対パスを使用することで、固定IP依存を避ける
            # Ingress経由でアクセス可能なURLは自動判定される
            # Dify Webは環境変数が空の場合、自動的に相対パスを使用する
            - name: SERVER_URL
              value: ""
            - name: CONSOLE_URL
              value: ""
            - name: APP_API_URL
              value: ""
            - name: CONSOLE_API_URL
              value: ""
            - name: CONSOLE_WEB_URL
              value: ""
            - name: APP_WEB_URL
              value: ""
            - name: SERVICE_API_URL
              value: ""
            - name: FILES_URL
              value: ""
          ports:
            - containerPort: 3000
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dify-web
  ports:
    - port: 80
      targetPort: 3000
