apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-web
  template:
    metadata:
      labels:
        app: dify-web
    spec:
      containers:
        - name: dify-web
          image: "{{ required "images.dify.repository is required" .Values.images.dify.repository }}:{{ required "images.dify.tag is required" .Values.images.dify.tag }}"
          envFrom:
            - secretRef:
                name: dify-secrets
          env:
            - name: SERVER_URL
              value: "{{ include "dify.externalURL" . }}"
            - name: CONSOLE_URL
              value: "{{ include "dify.externalURL" . }}"
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          # リソースやlivenessProbe等は後続で調整
---
apiVersion: v1
kind: Service
metadata:
  name: dify-web
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dify-web
  ports:
    - port: 80
      targetPort: 80

