{{- /*
  Secret自動生成方針:
  - lookup を使って既存Secretがあればそれを採用
  - なければ randAlphaNum 等で生成して Secret を作る
  - upgrade 時に値が変わらないようにする（重要）
*/}}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace "dify-secrets" }}
{{- $difySecretKey := "" }}
{{- $pluginDaemonKey := "" }}
{{- $difyInnerApiKey := "" }}
{{- if $existingSecret }}
  {{- /* 既存Secretがある場合は既存値を採用 */}}
  {{- $difySecretKey = index $existingSecret.data "difySecretKey" | b64dec }}
  {{- $pluginDaemonKey = index $existingSecret.data "pluginDaemonKey" | b64dec }}
  {{- $difyInnerApiKey = index $existingSecret.data "difyInnerApiKey" | b64dec }}
{{- else }}
  {{- /* 既存Secretがない場合は生成 */}}
  {{- $difySecretKey = randAlphaNum 64 }}
  {{- $pluginDaemonKey = randAlphaNum 64 }}
  {{- $difyInnerApiKey = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  difySecretKey: {{ $difySecretKey | b64enc }}
  pluginDaemonKey: {{ $pluginDaemonKey | b64enc }}
  difyInnerApiKey: {{ $difyInnerApiKey | b64enc }}
{{- if .Values.secrets.openaiApiKey }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | b64enc }}
{{- end }}

