apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DIFY_SECRET_KEY: {{ required "secrets.difySecretKey is required" .Values.secrets.difySecretKey }}
{{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey }}
{{- end }}

