{{- /*
  Secret自動生成方針:
  - lookup を使って既存Secretがあればそれを採用
  - なければ randAlphaNum 等で生成して Secret を作る
  - upgrade 時に値が変わらないようにする（重要）
  - PostgreSQL/Redis のパスワードも自動生成（PVCが残る限り同じ値が必要）
*/}}

{{- /* Dify Secrets */}}
{{- $existingDifySecret := lookup "v1" "Secret" .Release.Namespace "dify-secrets" }}
{{- $difySecretKey := "" }}
{{- $pluginDaemonKey := "" }}
{{- $difyInnerApiKey := "" }}
{{- if $existingDifySecret }}
  {{- /* 既存Secretがある場合は既存値を採用 */}}
  {{- $difySecretKey = index $existingDifySecret.data "difySecretKey" | b64dec }}
  {{- $pluginDaemonKey = index $existingDifySecret.data "pluginDaemonKey" | b64dec }}
  {{- $difyInnerApiKey = index $existingDifySecret.data "difyInnerApiKey" | b64dec }}
{{- else }}
  {{- /* 既存Secretがない場合は生成 */}}
  {{- $difySecretKey = randAlphaNum 64 }}
  {{- $pluginDaemonKey = randAlphaNum 64 }}
  {{- $difyInnerApiKey = randAlphaNum 64 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: dify-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  difySecretKey: {{ $difySecretKey | b64enc }}
  pluginDaemonKey: {{ $pluginDaemonKey | b64enc }}
  difyInnerApiKey: {{ $difyInnerApiKey | b64enc }}
{{- if .Values.secrets.openaiApiKey }}
  openaiApiKey: {{ .Values.secrets.openaiApiKey | b64enc }}
{{- end }}
---
{{- /* PostgreSQL Secrets */}}
{{- $existingPostgresSecret := lookup "v1" "Secret" .Release.Namespace "dify-postgresql" }}
{{- $postgresPassword := "" }}
{{- if $existingPostgresSecret }}
  {{- /* 既存Secretがある場合は既存値を採用（PVCが残る限り同じ値が必要） */}}
  {{- $postgresPassword = index $existingPostgresSecret.data "postgres-password" | b64dec }}
{{- else }}
  {{- /* 既存Secretがない場合は生成 */}}
  {{- $postgresPassword = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: dify-postgresql
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  postgres-username: {{ .Values.postgresql.auth.username | default "dify" }}
  postgres-password: {{ $postgresPassword }}
  postgres-database: {{ .Values.postgresql.auth.database | default "dify" }}
  # Compatibility: add 'password' key for backward compatibility (same value as postgres-password)
  password: {{ $postgresPassword }}
---
{{- /* Redis Secrets */}}
{{- $existingRedisSecret := lookup "v1" "Secret" .Release.Namespace "dify-redis" }}
{{- $redisPassword := "" }}
{{- if $existingRedisSecret }}
  {{- /* 既存Secretがある場合は既存値を採用 */}}
  {{- $redisPassword = index $existingRedisSecret.data "password" | b64dec }}
{{- else }}
  {{- /* 既存Secretがない場合は生成 */}}
  {{- $redisPassword = randAlphaNum 32 }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: dify-redis
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  password: {{ $redisPassword }}
