{{- if .Values.weaviate.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dify-weaviate-0
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.weaviate.persistence.size | default "50Gi" }}
  storageClassName: {{ if .Values.weaviate.persistence.storageClass }}{{ .Values.weaviate.persistence.storageClass }}{{ else }}{{ .Values.storage.storageClassName | default "nutanix-volume" }}{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dify-weaviate
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dify-weaviate
  template:
    metadata:
      labels:
        app: dify-weaviate
    spec:
      containers:
        - name: weaviate
          image: semitechnologies/weaviate:{{ .Values.weaviate.image.tag | default "1.25.0" }}
          env:
            - name: PERSISTENCE_DATA_PATH
              value: /var/lib/weaviate
            - name: QUERY_DEFAULTS_LIMIT
              value: "25"
            - name: AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED
              value: "true"
            - name: PERSISTENCE_ENABLED
              value: "true"
            - name: DEFAULT_VECTORIZER_MODULE
              value: "none"
            - name: ENABLE_MODULES
              value: ""
            - name: CLUSTER_HOSTNAME
              value: "node1"
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 50051
              name: grpc
          volumeMounts:
            - name: data
              mountPath: /var/lib/weaviate
          readinessProbe:
            httpGet:
              path: /v1/.well-known/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /v1/.well-known/live
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-dify-weaviate-0
---
apiVersion: v1
kind: Service
metadata:
  name: dify-weaviate
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dify-weaviate
  ports:
    - port: 8080
      targetPort: 8080
      name: http
    - port: 50051
      targetPort: 50051
      name: grpc
{{- end }}
